---
label: Products
hide_body: true
fields:
- name: name
  type: text
  config:
    required: false
  label: Name
  description: Name of the Product
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Description
  description: Description of the product
- name: thumbnail
  type: file
  config:
    maxSize: 64
  label: Thumbnail
  description: Image of the product
